kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: tailscale
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: node_exporter_ci
          static_configs:
          - targets: 
              - '10.24.59.5:9100'
              - '10.24.59.6:9100'
  alertmanager:
    config:
      route:
        group_by: ['namespace']
        reciever: discord
      receivers:
        - name: discord
          discord_config:
            - send_resolved: true
              webhook_url: "https://discordapp.com/api/webhooks/1293221116961362011/EThjHFSwhmcL6_c2zd9bvkhfk2JcC5WqCG_OHlQ7RuBMgjU3ybIymqxST8BS0Z1Mk_Ff" 