---
apache:
  ingress:
    enabled: true
    ingressClassName: "tailscale"
    pathType: Prefix
    extraRules:
    - http:
        paths:
          - backend:
              service: apacheweb
                port:
                  name: http
            path: /
            pathType: Prefix
  service:
    type: ClusterIP
    ports:
      http: 80
  htdocsConfigMap: "html-configmap"

  