---
apache:
  ingress:
    enabled: true
    ingressClassName: "tailscale"
    pathType: Prefix
    extraRules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "apacheweb"
                port:
                  name: http       
  service:
    type: ClusterIP
    ports:
      http: 80
  htdocsConfigMap: "html-configmap"

  