---
apache:
  ingress:
    enabled: true
    ingressClassName: "tailscale"
    pathType: prefix
    hostname: 
  service:
    type: ClusterIP
    ports:
      http: 80
  htdocsConfigMap: "html-configmap"